language: php

php:
  - 5.4
  - 5.5

env:
  global:
    - PLUGIN_NAME=PenaltyInterest
    - secure: NVrB8cZ92I1KzwHd0r4FBqt57pG7w8/3OzOZl29eG6IyEDxWnS/yk/NHTm7OLONZ34LVOWr7CVWmu0YGYj8l6gjjR/YF1gGrgUNX7pa5zasxWKx5/mqp9MQ2SxQr883KcKqVCta14vipmNjiAWYG/bpxYVC4OtE7b2g+PiZmVJKIF5/OaBnGuGxq+6nKR/behIH2pLRAX2HwfXtxfomIxz+QLmP1RoiLr4mUI5T74j6SLPMRhcj3RRzy57bnq1vNSPGQjjawJt80JP+uQRt4J4PN1/HKci9h5FGqWHZfa3x0hTTwh8pvBTp0gbuAcEMRBUGNgIjnoJqgaS2kZ6nCIl0BPjGUVmwWCaQXu0UnZuXnbRn31Mef8TRalIyJyrte4zW0juKtRAc17xcFduBGFHH4fqBglSq0IzaRh6F77tuGiJVHqkW2tqFgSiAhhTkG9PrfmoKjT2jDCIHguIz+G0XursOp4kyY1XZs262pJLXMKtXNLU+m9U3FMKs738jy3IVWk808xg//yvfPRkRuaU2MJq/Vo42VkrPUReXZgw2GK2TzCI/W0Z7zvN1BmUkLDGv5TC8caqgLLDuqe+eTVXcEjTyMpKxRvovEa2TFB+ZAu9Yvi0ng/K6kutCd9fhBR4wCoyAok78bllpVNcpYEc2um6YTIMdl1bvSlDJ08wY=

  matrix:
    - CAKE_VERSION=2.5
    - CAKE_VERSION=2.6

matrix:
  include:
    - php: 5.5
      env:
        - CAKE_VERSION=2.6
        - COVERALLS=1
    - php: 5.4
      env:
        - PHPCS=1

before_script:
  - composer config -g github-oauth.github.com $GITHUB_TOKEN
  - git clone -b master https://github.com/FriendsOfCake/travis.git --depth 1 ../travis
  - 'sed -i'''' ''s|curl |curl -H "Authorization: token \$GITHUB_TOKEN" |g'' ../travis/before_script.sh'
  - ../travis/before_script.sh
  - mv ../cakephp-penaltyinterest ../cakephp/app/Plugin/PenaltyInterest
  - cd ..
  - cd ..
  - cd ..
  - ls -al
  - chmod -R 777 tmp
  - sh -c "mysql -e 'CREATE DATABASE cakephp_test;'"
  - echo "<?php
    class DATABASE_CONFIG {
    public \$test = array(
      'datasource' => 'Database/Mysql',
      'database' => 'cakephp_test',
      'host' => '0.0.0.0',
      'login' => 'travis',
      'persistent' => false,
    );
    }" > Config/database.php

script:
  - ../travis/script.sh

after_success:
  - ../travis/after_success.sh

notifications:
  email: false